SELECT CONCAT(EMP_FNAME, " ", EMP_LNAME) AS Name, YEAR(curdate())-YEAR(EMP_DOB) as Age FROM professor
ORDER BY Age DESC
LIMIT 10;

SELECT ROUND(AVG(STU_GPA), 2) FROM student
WHERE DEPT_CODE = 'CIS';

SELECT COUNT(DISTINCT(COURSE_CODE)) AS '# of Courses' FROM course
WHERE DEPT_CODE IN ('CIS', 'MATH', 'BIOL', 'ENG') AND CRS_CREDIT = 3;

SELECT DEPT_CODE, COUNT(*) AS 'Total # of Students' FROM student
WHERE DEPT_CODE IN ('CIS', 'MATH', 'BIOL', 'ENG')
GROUP BY DEPT_CODE
ORDER BY `Total # of Students` DESC;

SELECT DEPT_CODE, ROUND(AVG(STU_GPA), 2) as 'Average GPA' FROM student
GROUP BY DEPT_CODE
ORDER BY `Average GPA` DESC;

SELECT DEPT_CODE, ROUND(AVG(STU_GPA), 2) as 'Average GPA' FROM student
GROUP BY DEPT_CODE
HAVING ROUND(AVG(STU_GPA), 2) > 3.00
ORDER BY `Average GPA` DESC;

SELECT
    STU_CLASS,
    COUNT(DISTINCT STU_NUM) AS "Total students",
    ROUND(AVG(STU_GPA), 2) AS "Average GPA"
FROM student
WHERE STU_GPA IS NOT NULL
GROUP BY STU_CLASS
ORDER BY STU_CLASS;


